name: Build

on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.os }} (${{ matrix.dotnet }})
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: ['3.1.406', '5.0.200']

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
    
      - run: dotnet clean && dotnet nuget locals all --clear
      - run: dotnet build -c Release