name: Build

on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.os }} (${{ matrix.dotnet }})
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['3.1.407', '5.0.201']
        include:
          - dotnet: 3.1.407
            target-framework: netcoreapp3.1
          - dotnet: 5.0.201
            target-framework: net5.0

    steps:
      - name: Branch checkout
        uses: actions/checkout@v2.3.4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
    
      - name: Clean repo folder and clear nuget cache
        run: dotnet clean && dotnet nuget locals all --clear
      
      - name: Build
        run: dotnet build --configuration Release --framework ${{ matrix.target-framework }}

      - name: Test
        run: dotnet test --configuration Release --framework ${{ matrix.target-framework }}

  