name: Publish

on:
  release:
    types: [published]

jobs:

  publish:
    name: Publish to github packages
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Branch checkout
        uses: actions/checkout@v2.3.4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/joaope/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
      - name: Clean repo folder and clear nuget cache
        run: dotnet clean && dotnet nuget locals all --clear
      
      - name: Pack
        run: dotnet pack --configuration Release --output asana_out ./src/Asana/Asana.csproj

      - name: Publish
        run: dotnet nuget push ./asana_out/*.nupkg --skip-duplicate --no-symbols true